#!/bin/sh

cygwin=false;
case "`uname`" in
  CYGWIN*) cygwin=true ;;
esac

SVNKIT_HOME=`dirname $0`
SVNKIT_HOME=`cd "$SVNKIT_HOME" ; pwd`

SVNKIT_CP="$SVNKIT_HOME/lib/*:$SVNKIT_HOME/../atlassian-bamboo/WEB-INF/lib/*"

if $cygwin ; then
  SVNKIT_CP=`cygpath --windows --path "$SVNKIT_CP"`
fi

SVNKIT_VM_OPTIONS="-Dsun.io.useCanonCaches=false -Djava.util.logging.config.file=$SVNKIT_HOME/lib/logging.properties.disabled"

SVNKIT_MAINCLASS=org.tmatesoft.svn.cli.SVN

java -version
java $YOURKIT $SVNKIT_VM_OPTIONS $SSH -Dsvnkit.useJNA=true -Dsvnkit.symlinks=false -Djava.util.logging.config.file=logging.properties -cp $SVNKIT_CP $SVNKIT_MAINCLASS "$@"
