<span[#rt/]
[#if (parameters.id)?has_content]
 id="${parameters.id?html}"[#rt/]
[/#if]
[#if parameters.cssClass??]
 class="${parameters.cssClass?html}"[#rt/]
[/#if]
[#if parameters.cssStyle??]
 style="${parameters.cssStyle?html}"[#rt/]
[/#if]
[#if parameters.title??]
 title="${parameters.title?html}"[#rt/]
[/#if]
[#if parameters.for??]
 for="${parameters.for?html}"[#rt/]
[/#if]
>[#rt/]
[#if parameters.nameValue??]
[#if parameters.dateValue??]
    [#if parameters.dateFormat??]
        [@ww.date name='parameters.dateValue' format='${parameters.dateFormat}' /][#t/]
    [#else]
        [@ww.date name='parameters.dateValue' /]
    [/#if]
[#elseif parameters.escape??]
    [@ww.property value="parameters.nameValue" escapeHtml=parameters.escape/][#t/]
[#elseif parameters.escapeHtml??]
    [@ww.property value="parameters.nameValue" escapeHtml=parameters.escapeHtml/][#t/]
[#else]
    [@ww.property value="parameters.nameValue" /][#t/]
[/#if]
[/#if]
</span>
