<pre[#rt/]
[#if (parameters.id)?has_content]
 id="${parameters.id?html}"[#rt/]
[/#if]
[#if parameters.cssClass??]
 class="${parameters.cssClass?html}"[#rt/]
[/#if]
[#if parameters.cssStyle??]
 style="${parameters.cssStyle?html}"[#rt/]
[/#if]
>[#rt/]
[#if parameters.nameValue??]
    [@ww.property value="parameters.nameValue" /][#t/]
[/#if]
</pre>
