[#include "/${parameters.templateDir}/simple/dynamic-field-parameters.ftl" /]
[#assign itemKey = parameters.fieldValue /]
[#assign itemValue = parameters.fieldValue /]

<input type="radio" name="${parameters.name?html}" id="${parameters.id?html}${itemKey?html}"[#rt/]
[#if tag.contains(parameters.nameValue, itemKey) || (parameters.nameValue?? && parameters.nameValue?string == itemKey)]
 checked="checked"[#rt/]
[/#if]
[#if itemKey??]
 value="${itemKey?html}"[#rt/]
[/#if]
[#if parameters.disabled!false]
 disabled="disabled"[#rt/]
[/#if]
[#if parameters.tabindex??]
 tabindex="${parameters.tabindex?html}"[#rt/]
[/#if]
[#if parameters.cssClass??]
 class="${parameters.cssClass?html}"[#rt/]
[/#if]
[#if parameters.cssStyle??]
 style="${parameters.cssStyle?html}"[#rt/]
[/#if]
[#if parameters.title??]
 title="${parameters.title?html}"[#rt/]
[/#if]
[#include "/${parameters.templateDir}/simple/scripting-events.ftl" /]
/>[#rt/]