[#if parameters.type?? && parameters.type=="button"]
<button type="submit"[#rt/]
[#if parameters.name??]
 name="${parameters.name?html}"[#rt/]
[/#if]
[#if parameters.nameValue??]
 value="[@ww.property value="parameters.nameValue"/]"[#rt/]
[/#if]
[#if parameters.cssClass??]
 class="${parameters.cssClass?html}"[#rt/]
[/#if]
[#if parameters.cssStyle??]
 style="${parameters.cssStyle?html}"[#rt/]
[/#if]
[#include "/${parameters.templateDir}/simple/scripting-events.ftl"/]
>[#if parameters.label??][@ww.property value="parameters.label"/][#rt/][/#if]</button>
[#else]
[#if parameters.type?? && parameters.type=="image"]
<input type="image"[#rt/]
[#if parameters.label??]
 alt="${parameters.label?html}"[#rt/]
[/#if]
[#if parameters.src??]
 src="${parameters.src?html}"[#rt/]
[/#if]
[#else]
<input type="submit"[#rt/]
[/#if]
[#if parameters.name??]
 name="${parameters.name?html}"[#rt/]
[/#if]
[#if parameters.nameValue??]
 value="[@ww.property value="parameters.nameValue"/]"[#rt/]
[/#if]
[#if parameters.disabled?? && parameters.disabled?is_boolean && parameters.disabled]
  disabled="true"[#rt/]
[/#if]
[#if parameters.cssClass??]
 class="${parameters.cssClass?html}"[#rt/]
[/#if]
[#if parameters.cssStyle??]
 style="${parameters.cssStyle?html}"[#rt/]
[/#if]
[#if parameters.title??]
 title="${parameters.title?html}"[#rt/]
[#elseif parameters.titleKey??]
 title="[@ww.text name='${parameters.titleKey?html}' /]"[#rt/]
[/#if]
[#if parameters.id??]
 id="${parameters.id?html}"[#rt/]
[/#if]
[#include "/${parameters.templateDir}/simple/scripting-events.ftl" /]
[#if !(parameters.hideAccessKey!true) || parameters.customAccessKey??]
    [#if parameters.customAccessKey??]
 accesskey="${parameters.customAccessKey}"[#rt/]
    [#else]
 accesskey="${action.getText('global.key.submit')}"[#rt/]
    [/#if]
[/#if]
[#if parameters.tabindex??]
 tabindex="${parameters.tabindex?html}"[#rt/]
[/#if]
/>[#t/]
[/#if]
