<textarea[#rt/]
 spellcheck="${parameters.spellcheck!"false"?html}"[#rt/]
 name="${parameters.name!""?html}"[#rt/]
[#if parameters.cols??] cols="${parameters.cols?html}"[/#if][#rt/]
[#if parameters.rows??]  rows="${parameters.rows?html}"[/#if][#rt/]
[#if parameters.wrap??]
 wrap="${parameters.wrap?html}"[#rt/]
[/#if]
[#if parameters.disabled!false]
 disabled="disabled"[#rt/]
[/#if]
[#if parameters.readonly!false]
 readonly="readonly"[#rt/]
[/#if]
[#if parameters.tabindex??]
 tabindex="${parameters.tabindex?html}"[#rt/]
[/#if]
[#if parameters.id??]
 id="${parameters.id?html}"[#rt/]
[/#if]
[#-- CSS Class--]
 class="[#rt/]
[#if cssClass??]
    ${cssClass?html} [#t]
[#elseif parameters.cssClass??]
    ${parameters.cssClass?html} [#t]
[#else]
    textField [#t]
[/#if]
[#if fieldErrors[parameters.name]?has_content]
    errorField [#t]
[/#if]
[#if parameters.fullWidthField!false]
    full-width-field [#t]
[#elseif parameters.longField!false]
    long-field [#t]
[#elseif parameters.mediumField!false]
    medium-field [#t]
[#elseif parameters.shortField!false]
    short-field [#t]
[/#if]
"[#lt]
[#-- END CSS Class --]
[#if parameters.cssStyle??]
 style="${parameters.cssStyle?html}"[#rt/]
[/#if]
[#if parameters.title??]
 title="${parameters.title?html}"[#rt/]
[/#if]
[#if parameters.placeholderKey??]
 placeholder="[@ww.text name=parameters.placeholderKey /]"[#t/]
[/#if]
[#if parameters.autofocus?? && parameters.autofocus == true]
 autofocus[#t/]
[/#if]
[#include "/${parameters.templateDir}/simple/scripting-events.ftl" /]
>[#rt/]
[#if parameters.nameValue??]
[@ww.property value="parameters.nameValue"/][#t/]
[/#if]
</textarea>
