[#if credentialsName?has_content]
    [@s.checkbox labelKey='credentials.ssh.change' toggle='true' name='updateSshKey' /]
    [@ui.bambooSection dependsOn='updateSshKey' showOn=true]
        [@s.textarea labelKey='credentials.ssh.key' name='sshKey' required=true/]
        [@s.password labelKey='credentials.ssh.passphrase' name='sshPassphrase' /]
    [/@ui.bambooSection]
[#else]
    [@s.hidden name='updateSshKey' value='true' /]
    [@s.textarea labelKey='credentials.ssh.key' name='sshKey' required=true/]
    [@s.password labelKey='credentials.ssh.passphrase' name='sshPassphrase' /]
[/#if]