[@s.textfield labelKey='credentials.usernamePassword.username' name='username' required='true'/]
[#if credentialsName?has_content]
    [@s.checkbox labelKey='credentials.usernamePassword.password.change' toggle='true' name='updatePassword' /]
    [@ui.bambooSection dependsOn='updatePassword' showOn=true]
        [@s.password labelKey='credentials.usernamePassword.password' name='password' /]
    [/@ui.bambooSection]
[#else]
    [@s.hidden name='updatePassword' value='true' /]
    [@s.password labelKey='credentials.usernamePassword.password' name='password' /]
[/#if]
